[project]
name = "zensync-meditation-assets"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.zensync-core]
path = "contracts/zensync-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
